// <auto-generated />
using System;
using System.Collections.Generic;
using Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20260429084905_DM")]
    partial class DM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.AlbumAggregate.AlbumEntity.Album", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<byte>("_accessLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("access_level");

                    b.Property<long>("_author")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long[]>("_collaborators")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("collaborators");

                    b.Property<bool>("_removed")
                        .HasColumnType("boolean")
                        .HasColumnName("removed");

                    b.Property<bool>("_updateCoverAutomatically")
                        .HasColumnType("boolean")
                        .HasColumnName("update_cover_automatically");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("_author")
                        .HasDatabaseName("ix_albums_author_id");

                    b.ToTable("albums", "domain");
                });

            modelBuilder.Entity("Domain.CategoryAggregate.CategoryEntity.Category", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "domain");
                });

            modelBuilder.Entity("Domain.UserAggregate.UserEntity.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("_email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("_refreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<byte[]>("_roles")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("roles");

                    b.Property<string>("_username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "_password", "Domain.UserAggregate.UserEntity.User._password#Password", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("password_hash");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("password_salt");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("_username")
                        .IsUnique()
                        .HasDatabaseName("ix_users__username");

                    b.ToTable("users", "domain");
                });

            modelBuilder.Entity("Domain.AlbumAggregate.AlbumEntity.Album", b =>
                {
                    b.HasOne("Domain.UserAggregate.UserEntity.User", null)
                        .WithMany()
                        .HasForeignKey("_author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_albums_users_author_id");

                    b.OwnsMany("Domain.AlbumAggregate.AlbumEntity.Subscribe", "_subscribes", b1 =>
                        {
                            b1.Property<long>("User")
                                .HasColumnType("bigint")
                                .HasColumnName("user");

                            b1.Property<long>("Album")
                                .HasColumnType("bigint")
                                .HasColumnName("album");

                            b1.HasKey("User", "Album")
                                .HasName("pk_subscribes");

                            b1.HasIndex("Album")
                                .HasDatabaseName("ix_subscribes_album");

                            b1.ToTable("subscribes", "domain");

                            b1.WithOwner()
                                .HasForeignKey("Album")
                                .HasConstraintName("fk_subscribes_albums_album");

                            b1.HasOne("Domain.UserAggregate.UserEntity.User", null)
                                .WithMany()
                                .HasForeignKey("User")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_subscribes_users_user");
                        });

                    b.OwnsMany("Domain.AlbumAggregate.ImageEntity.Image", "_images", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("_uploader")
                                .HasColumnType("bigint")
                                .HasColumnName("uploader_id");

                            b1.Property<long>("album_id")
                                .HasColumnType("bigint")
                                .HasColumnName("album_id");

                            b1.HasKey("Id")
                                .HasName("pk_images");

                            b1.HasIndex("_uploader")
                                .HasDatabaseName("ix_images_uploader_id");

                            b1.HasIndex("album_id")
                                .HasDatabaseName("ix_images_album_id");

                            b1.ToTable("images", "domain");

                            b1.HasOne("Domain.UserAggregate.UserEntity.User", null)
                                .WithMany()
                                .HasForeignKey("_uploader")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_images_users_uploader_id");

                            b1.WithOwner()
                                .HasForeignKey("album_id")
                                .HasConstraintName("fk_images_albums_album_id");

                            b1.OwnsMany("Domain.AlbumAggregate.ImageEntity.Like", "_likes", b2 =>
                                {
                                    b2.Property<long>("User")
                                        .HasColumnType("bigint")
                                        .HasColumnName("user");

                                    b2.Property<long>("Image")
                                        .HasColumnType("bigint")
                                        .HasColumnName("image");

                                    b2.HasKey("User", "Image")
                                        .HasName("pk_likes");

                                    b2.HasIndex("Image")
                                        .HasDatabaseName("ix_likes_image");

                                    b2.ToTable("likes", "domain");

                                    b2.WithOwner()
                                        .HasForeignKey("Image")
                                        .HasConstraintName("fk_likes_images_image");

                                    b2.HasOne("Domain.UserAggregate.UserEntity.User", null)
                                        .WithMany()
                                        .HasForeignKey("User")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired()
                                        .HasConstraintName("fk_likes_users_user");
                                });

                            b1.OwnsOne("Domain.AlbumAggregate.ImageEntity.ImageStatus", "_status", b2 =>
                                {
                                    b2.Property<long>("ImageId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<DateTime?>("RemovedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("_status_removed_at");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("_status_value");

                                    b2.HasKey("ImageId");

                                    b2.ToTable("images", "domain");

                                    b2.WithOwner()
                                        .HasForeignKey("ImageId")
                                        .HasConstraintName("fk_image_image_id");
                                });

                            b1.Navigation("_likes");

                            b1.Navigation("_status");
                        });

                    b.Navigation("_images");

                    b.Navigation("_subscribes");
                });

            modelBuilder.Entity("Domain.UserAggregate.UserEntity.User", b =>
                {
                    b.OwnsMany("Domain.UserAggregate.IdentityEntity.Identity", "_identities", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<byte>("_provider")
                                .HasColumnType("smallint")
                                .HasColumnName("provider");

                            b1.Property<long>("_providerUserId")
                                .HasColumnType("bigint")
                                .HasColumnName("provider_user_id");

                            b1.Property<long>("user_id")
                                .HasColumnType("bigint")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_identities");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_identities_user_id");

                            b1.ToTable("identities", "domain");

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_identities_users_user_id");
                        });

                    b.Navigation("_identities");
                });
#pragma warning restore 612, 618
        }
    }
}
