// <auto-generated />
using System;
using System.Collections.Generic;
using Domain.Event;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260506162354_DCM2")]
    partial class DCM2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("event")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Event.DomainEventUnit", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("ETag")
                        .HasColumnType("integer")
                        .HasColumnName("e_tag");

                    b.Property<long>("GrainId")
                        .HasColumnType("bigint")
                        .HasColumnName("grain_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Value", "Domain.Event.DomainEventUnit.Value#DomainEventBase", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Id");

                            b1.Property<DateTime>("Timestamp");

                            b1
                                .ToJson("value")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_events_timestamp");

                    b.HasIndex("GrainId", "ETag")
                        .IsUnique()
                        .HasDatabaseName("ix_events_grain_id_e_tag");

                    b.ToTable("events", "event");
                });
#pragma warning restore 612, 618
        }
    }
}
