// <auto-generated />
using System;
using Domain.Database;
using Domain.Event;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    partial class DomainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None)
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.Event.DomainEventUnit", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("ETag")
                        .HasColumnType("integer")
                        .HasColumnName("e_tag");

                    b.Property<long>("GrainId")
                        .HasColumnType("bigint")
                        .HasColumnName("grain_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DomainEventBase>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("EventId")
                        .HasName("pk_events");

                    b.HasIndex("Timestamp")
                        .IsUnique()
                        .HasDatabaseName("ix_events_timestamp");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_events_type");

                    b.HasIndex("GrainId", "ETag")
                        .IsUnique()
                        .HasDatabaseName("ix_events_grain_id_e_tag");

                    b.ToTable("events", "domain");
                });
#pragma warning restore 612, 618
        }
    }
}
