// <auto-generated />
using System.Collections.Generic;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20260506135015_DM")]
    partial class DM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("domain")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.DomainStateUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ETag")
                        .HasColumnType("integer")
                        .HasColumnName("e_tag");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Value", "Domain.DomainStateUnit.Value#DomainStateBase", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("RecordExists");

                            b1
                                .ToJson("value")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_snapshots");

                    b.HasIndex("ETag")
                        .HasDatabaseName("ix_snapshots_e_tag");

                    b.ToTable("snapshots", "domain");
                });
#pragma warning restore 612, 618
        }
    }
}
