// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Query
{
    public partial class QueryDbContextModel
    {
        private QueryDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("52cf9353-a9b8-40e1-9141-988fe6c1b954"), entityTypeCount: 6)
        {
        }

        partial void Initialize()
        {
            var albumModel = AlbumModelEntityType.Create(this);
            var subscribeModel = SubscribeModelEntityType.Create(this);
            var categoryModel = CategoryModelEntityType.Create(this);
            var imageModel = ImageModelEntityType.Create(this);
            var likeModel = LikeModelEntityType.Create(this);
            var userModel = UserModelEntityType.Create(this);

            AlbumModelEntityType.CreateForeignKey1(albumModel, userModel);
            AlbumModelEntityType.CreateForeignKey2(albumModel, categoryModel);
            SubscribeModelEntityType.CreateForeignKey1(subscribeModel, albumModel);
            SubscribeModelEntityType.CreateForeignKey2(subscribeModel, userModel);
            ImageModelEntityType.CreateForeignKey1(imageModel, albumModel);
            ImageModelEntityType.CreateForeignKey2(imageModel, userModel);
            ImageModelEntityType.CreateForeignKey3(imageModel, userModel);
            LikeModelEntityType.CreateForeignKey1(likeModel, imageModel);
            LikeModelEntityType.CreateForeignKey2(likeModel, userModel);

            AlbumModelEntityType.CreateSkipNavigation1(albumModel, userModel, subscribeModel);
            ImageModelEntityType.CreateSkipNavigation1(imageModel, userModel, likeModel);
            UserModelEntityType.CreateSkipNavigation1(userModel, albumModel, subscribeModel);
            UserModelEntityType.CreateSkipNavigation2(userModel, imageModel, likeModel);

            AlbumModelEntityType.CreateAnnotations(albumModel);
            SubscribeModelEntityType.CreateAnnotations(subscribeModel);
            CategoryModelEntityType.CreateAnnotations(categoryModel);
            ImageModelEntityType.CreateAnnotations(imageModel);
            LikeModelEntityType.CreateAnnotations(likeModel);
            UserModelEntityType.CreateAnnotations(userModel);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.7");
            AddAnnotation("Relational:DefaultSchema", "query");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
