// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storage.Database;

#nullable disable

namespace Storage.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20260429085002_SM")]
    partial class SM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("storage")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Storage.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("RetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.ToTable("messages", "storage");

                    b.HasDiscriminator<string>("type").IsComplete(true).HasValue("OutboxMessage");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Storage.Albums.Messages.AlbumCoverUpdatedMessage", b =>
                {
                    b.HasBaseType("Storage.OutboxMessage");

                    b.Property<long>("Album")
                        .HasColumnType("bigint")
                        .HasColumnName("album");

                    b.Property<string>("File")
                        .HasColumnType("text")
                        .HasColumnName("file");

                    b.ToTable("messages", "storage", t =>
                        {
                            t.Property("File")
                                .HasColumnName("album_cover_updated_message_file");
                        });

                    b.HasDiscriminator().HasValue("cover_updated");
                });

            modelBuilder.Entity("Storage.Images.Messages.ImageAddedMessage", b =>
                {
                    b.HasBaseType("Storage.OutboxMessage");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file");

                    b.Property<long>("ImageId")
                        .HasColumnType("bigint")
                        .HasColumnName("image_id");

                    b.ToTable("messages", "storage", t =>
                        {
                            t.Property("ImageId")
                                .HasColumnName("image_added_message_image_id");
                        });

                    b.HasDiscriminator().HasValue("image_added");
                });

            modelBuilder.Entity("Storage.Images.Messages.ImageDeletedMessage", b =>
                {
                    b.HasBaseType("Storage.OutboxMessage");

                    b.Property<long>("ImageId")
                        .HasColumnType("bigint")
                        .HasColumnName("image_id");

                    b.ToTable("messages", "storage");

                    b.HasDiscriminator().HasValue("image_deleted");
                });

            modelBuilder.Entity("Storage.Users.Messages.AvatarUpdatedMessage", b =>
                {
                    b.HasBaseType("Storage.OutboxMessage");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable("messages", "storage");

                    b.HasDiscriminator().HasValue("avatar_updated");
                });

            modelBuilder.Entity("Storage.Users.Messages.HeaderUpdatedMessage", b =>
                {
                    b.HasBaseType("Storage.OutboxMessage");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ToTable("messages", "storage", t =>
                        {
                            t.Property("Image")
                                .HasColumnName("header_updated_message_image");

                            t.Property("UserId")
                                .HasColumnName("header_updated_message_user_id");
                        });

                    b.HasDiscriminator().HasValue("header_updated");
                });
#pragma warning restore 612, 618
        }
    }
}
