// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Query;
using Query.Database;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(QueryDbContext), typeof(QueryDbContextModel))]
