using Microsoft.CodeAnalysis;

namespace App.SourceGen;

[Generator]
public sealed class CssGenerator : IIncrementalGenerator
{
    // C# keywords that need @ escaping when used as identifiers
    private static readonly HashSet<string> s_keywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var cssFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".module.css", StringComparison.Ordinal))
            .Select((f, _) => (Path: f.Path, Content: f.GetText()?.ToString() ?? ""))
            .Collect();

        context.RegisterSourceOutput(cssFiles, (spc, files) =>
        {
            if (files.IsDefaultOrEmpty) return;

            var sorted = files.OrderBy(f => f.Path, StringComparer.Ordinal).ToArray();

            foreach (var f in sorted)
            {
                var scope = GetScope(f.Path);
                if (scope is null) continue;
                if (f.Content.Length == 0) continue;

                var tokens = CssTokenizer.Tokenize(f.Content);
                var rules = CssParser.Parse(tokens);
                var classes = CssParser.ExtractLocalClasses(rules);
                if (classes.Count == 0) continue;

                var ns = ResolveNamespace(f.Path);
                spc.AddSource($"{scope}.Css.g.cs",
                    GenerateCssClass(scope, classes, ns));
            }
        });
    }

    // "LoginPage.module.css" → "LoginPage", "global.module.css" → null
    private static string? GetScope(string path)
    {
        var name = System.IO.Path.GetFileName(path);
        if (!name.EndsWith(".module.css", StringComparison.Ordinal)) return null;
        name = name.Substring(0, name.Length - ".module.css".Length);
        if (name is "global" || !IsValidTypeName(name)) return null;
        return name;
    }

    // Map file path to namespace. All component CSS lives under Components/.
    private static string ResolveNamespace(string path)
    {
        var relative = path.Replace('\\', '/');
        var idx = relative.LastIndexOf("/src/App/");
        if (idx < 0) return "App.Components";
        var projectRelative = relative.Substring(idx + "/src/App/".Length);
        var dir = System.IO.Path.GetDirectoryName(projectRelative)?.Replace('/', '.') ?? "";
        return string.IsNullOrEmpty(dir) ? "App" : "App." + dir;
    }

    private static bool IsValidTypeName(string name)
    {
        if (string.IsNullOrEmpty(name)) return false;
        if (!char.IsLetter(name[0]) && name[0] != '_') return false;
        for (var i = 1; i < name.Length; i++)
        {
            if (!char.IsLetterOrDigit(name[i]) && name[i] != '_') return false;
        }
        return true;
    }

    private static string GenerateCssClass(string componentName, HashSet<string> classes, string ns)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"partial class {componentName}");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Css");
        sb.AppendLine("    {");
        foreach (var cls in classes.OrderBy(c => c))
        {
            var fieldName = EscapeIdentifier(cls.Replace('-', '_'));
            sb.AppendLine($"        public const string {fieldName} = \"{componentName}-{cls}\";");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    // Escape C# keywords with @ prefix; also ensure valid identifier start
    private static string EscapeIdentifier(string name)
    {
        if (s_keywords.Contains(name)) return "@" + name;
        if (name.Length > 0 && char.IsDigit(name[0])) return "_" + name;
        return name;
    }
}
